name: CI Test

on:
  push:
    branches:
      - main
      - release
      - develop
  pull_request:
    branches:
      - main
      - release
      - develop

permissions:
  contents: read
  issues: read
  checks: write
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Repository 가져오기
        uses: actions/checkout@v3

      - name: JDK 11 설치
        uses: actions/setup-java@v1
        with:
          java-version: 11
          distribution: 'temurin'

      - name: Gradle 명령을 위한 권한 부여
        run: chmod +x gradlew

      - name: Gradle Build 수행!
        run: ./gradlew build

      - name: 테스트 결과를 PR-Comment 로 등록
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: '**/build/test-results/test/TEST-*.xml'

      - name: 테스트 실패 시, 실패한 코드 라인에 Check Comment 를 등록
        uses: mikepenz/action-junit-report@v3
        if: always()
        with:
          report_paths: '**/build/test-results/test/TEST-*.xml'
          token: ${{ github.token }}